---
- name: Install Kubernetes packages
  ansible.builtin.dnf:
    name: "{{ kubernetes_packages }}"
    state: present
    disable_excludes: kubernetes
  tags:
    - kube-packages
    - install

- name: Enable kubelet
  ansible.builtin.service:
    name: kubelet
    enabled: true
    state: stopped
  tags:
    - kube-packages
    - install
