---
- name: Download Helm archive
  ansible.builtin.get_url:
    url: "https://get.helm.sh/helm-{{ helm_version }}-{{ helm_os }}-{{ helm_arch }}.tar.gz"
    dest: "/tmp/helm-{{ helm_version }}-{{ helm_os }}-{{ helm_arch }}.tar.gz"
    mode: "0644"

- name: Extract Helm archive
  ansible.builtin.unarchive:
    src: "/tmp/helm-{{ helm_version }}-{{ helm_os }}-{{ helm_arch }}.tar.gz"
    dest: /tmp
    remote_src: true

- name: Install Helm binary
  ansible.builtin.copy:
    src: "/tmp/{{ helm_os }}-{{ helm_arch }}/helm"
    dest: /usr/local/bin/helm
    owner: root
    group: root
    mode: "0755"
    remote_src: true

- name: Validate Helm
  ansible.builtin.command: /usr/local/bin/helm version
  register: helm_version_output
  changed_when: false

- name: Show Helm version
  ansible.builtin.debug:
    var: helm_version_output.stdout
