[build]
build01 ansible_host=PRIVATE_IP_BUILD

[k8s_control]
k8sctl01 ansible_host=PRIVATE_IP_K8S_CONTROL

[k8s_workers]
k8sworker01 ansible_host=PRIVATE_IP_WORKER1
k8sworker02 ansible_host=PRIVATE_IP_WORKER2
k8sworker03 ansible_host=PRIVATE_IP_WORKER3

[storage]
storage01 ansible_host=PRIVATE_IP_STORAGE

[login]
login01 ansible_host=PRIVATE_IP_LOGIN

[all:vars]
ansible_user=ec2-user
ansible_python_interpreter=/usr/bin/python3
