[build]
build01 ansible_host=172.31.8.208

[k8s_control]
k8sctl01 ansible_host=172.31.34.222

[k8s_workers]
k8sworker01 ansible_host=172.31.47.113
k8sworker02 ansible_host=172.31.36.7
k8sworker03 ansible_host=172.31.47.243

[storage]
storage01 ansible_host=172.31.34.122

[all:vars]
ansible_user=rocky
ansible_ssh_private_key_file=~/.ssh/HPC-KEY.pem
ansible_python_interpreter=/usr/bin/python3
