---
nfs_storageclass_namespace: nfs-provisioner
nfs_storageclass_name: nfs-client
nfs_storageclass_default: "true"

nfs_provisioner_release_name: nfs-subdir-external-provisioner
nfs_provisioner_repo_name: nfs-subdir-external-provisioner
nfs_provisioner_repo_url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/

nfs_server: "{{ hostvars[groups['storage'][0]].ansible_host }}"
nfs_export_path: /export/slinky
