---
galaxy_info:
  author: Avraham Rulevich
  description: Install and configure containerd runtime
  company: Ben-Gurion University
  license: MIT
  min_ansible_version: "2.15"

  platforms:
    - name: EL
      versions:
        - "9"

dependencies:
  - role: base
