---
- name: Install yum-utils
  ansible.builtin.package:
    name: yum-utils
    state: present

- name: Add Docker CE repository
  ansible.builtin.command:
    cmd: dnf config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo
    creates: /etc/yum.repos.d/docker-ce.repo
