---
containerd_service: containerd

containerd_packages:
  - containerd.io

containerd_kernel_modules:
  - overlay
  - br_netfilter

containerd_sysctl:
  net.bridge.bridge-nf-call-iptables: 1
  net.bridge.bridge-nf-call-ip6tables: 1
  net.ipv4.ip_forward: 1
